set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports resetn]
set_property -dict {PACKAGE_PIN V3 IOSTANDARD LVCMOS33} [get_ports lcd_e]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD LVCMOS33} [get_ports lcd_rs]
set_property -dict {PACKAGE_PIN AB1 IOSTANDARD LVCMOS33} [get_ports lcd_rw]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD LVCMOS33} [get_ports lcd_data[0]]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD LVCMOS33} [get_ports lcd_data[1]]
set_property -dict {PACKAGE_PIN Y3 IOSTANDARD LVCMOS33} [get_ports lcd_data[2]]
set_property -dict {PACKAGE_PIN AA3 IOSTANDARD LVCMOS33} [get_ports lcd_data[3]]
set_property -dict {PACKAGE_PIN AA5 IOSTANDARD LVCMOS33} [get_ports lcd_data[4]]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD LVCMOS33} [get_ports lcd_data[5]]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports lcd_data[6]]
set_property -dict {PACKAGE_PIN AA4 IOSTANDARD LVCMOS33} [get_ports lcd_data[7]]
create_clock -name clk -period 10.0 [get_ports clk]
